apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cp4foo-operator
rules:
  - apiGroups:
      - operator.ibm.com
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch